---
name: Docker Build and Push (Main Branch)

# Trigger on every push to the main branch
on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for commit SHA

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Note: You can also use DOCKERHUB_PASSWORD instead of DOCKERHUB_TOKEN
          # password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GIT_TAG=main-${{ steps.vars.outputs.sha_short }}
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ksusonic/3x-ui-exporter:latest
            ksusonic/3x-ui-exporter:${{ steps.vars.outputs.sha_short }}
          # To change the Docker image repository, modify the image name above
          # Format: <dockerhub-username>/<repository-name>:<tag>
          # Examples:
          #   myusername/my-3x-ui-exporter:latest
          #   myusername/my-3x-ui-exporter:${{ steps.vars.outputs.sha_short }}
